name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint (ruff)
        run: ruff check .

      - name: Format (black)
        run: black --check .

      - name: Imports (isort)
        run: isort --check-only .

      - name: Type check (mypy)
        run: mypy .

      - name: Tests (pytest)
        env:
          PYTHONNOUSERSITE: "1"
          PYTHONPATH: "."
        run: pytest -q --cov=pycwr --cov-report=xml

      - name: Build docs (mkdocs)
        run: mkdocs build --strict

